"""Type stubs for the Rust-backed `tomlplus._native` module."""

from typing import Any, Iterator, Optional, Union

__version__: str

class Annotation:
    name: str
    arg: Any
    is_metadata: bool
    is_validation: bool
    is_type_hint: bool
    is_tag: bool
    def __init__(self, name: str, arg: Any = ...) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TOMLPlusDocument:
    config: dict[str, Any]
    meta: dict[str, list[Annotation]]
    vars: dict[str, Any]
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def resolve(self, key_path: str, default: Any = ...) -> Any: ...
    def annotations(self, key_path: str) -> list[Annotation]: ...
    def has_annotation(self, key_path: str, name: str) -> bool: ...
    def tags(self, key_path: str) -> dict[str, str]: ...
    def required_keys(self) -> list[str]: ...
    def deprecated_keys(self) -> list[tuple[str, Optional[str]]]: ...
    def keys_with_tag(self, tag_name: str) -> list[tuple[str, str]]: ...

class TOMLPlusError(Exception): ...
class ParseError(TOMLPlusError): ...
class ValidationError(TOMLPlusError): ...
class VariableError(TOMLPlusError): ...

def parse(source: str) -> TOMLPlusDocument: ...
def validate(doc: TOMLPlusDocument) -> None: ...
def validate_all(doc: TOMLPlusDocument) -> list[ValidationError]: ...
def dumps(data: Union[TOMLPlusDocument, dict[str, Any]]) -> str: ...
