/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parse a TOML+ source string. Throws on a fatal parse error. */
export declare function parse(source: string): TomlplusDocument
/** Run the validator. Throws on the first failing constraint. */
export declare function validate(doc: TomlplusDocument): void
/** Run the validator. Returns *all* failing constraints as plain objects. */
export declare function validateAll(doc: TomlplusDocument): JValue
/** Serialise back to TOML+ text. */
export declare function dumps(doc: TomlplusDocument): string
export declare class TomlplusDocument {
  /** Resolve a dotted path; returns `null` when missing. */
  resolve(keyPath: string): JValue
  /** Annotations attached to a dotted key path: `[{name, arg}]`. */
  annotations(keyPath: string): JValue
  /** Is `name` among the annotations on `keyPath`? */
  hasAnnotation(keyPath: string, name: string): boolean
  /** `{ tagName: value, … }` for all `@tag` annotations at this path. */
  tags(keyPath: string): JValue
  /** All key paths annotated with `@required`. */
  requiredKeys(): Array<string>
  /** `[ [keyPath, message|null] ]` for all `@deprecated` keys. */
  deprecatedKeys(): JValue
  /** `[ [keyPath, value] ]` for keys with a `@tag: <tagName> = "value"`. */
  keysWithTag(tagName: string): JValue
  /** Whole config tree. */
  get config(): JValue
  /** User-defined `[vars]`. */
  get vars(): JValue
  /** All annotation metadata. */
  get meta(): JValue
  /** Top-level section/key names. */
  keys(): Array<string>
}
