#!/usr/bin/env python3
"""Cross-binding integration test for TOML+.

Parses `fixtures/kitchen-sink.tomlp` via every binding (Python, Node, WASM,
Java, .NET, Go, Ruby, plus the Rust CLI as the canonical reference) and
verifies they all produce the same JSON tree.

The canonical baseline lives in `fixtures/expected.json` (generated by the
Rust CLI). Each binding's output is normalised (numbers compared with
tolerance, dict ordering ignored) before comparison.

Run via the workspace dispatcher:

    py -3 release.py test -t cross-binding

…or directly:

    py -3 tests/cross-binding/run.py
"""

from __future__ import annotations

import json
import math
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# Force UTF-8 console on Windows so rich's glyphs survive cp1252.
for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

# Auto-install rich if missing (mirrors release.py).
try:
    from rich.console import Console
    from rich.table import Table
    from rich.theme import Theme
except ImportError:
    subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", "rich"], check=True)
    from rich.console import Console
    from rich.table import Table
    from rich.theme import Theme

console = Console(theme=Theme({
    "ok":    "bold green",
    "fail":  "bold red",
    "skip":  "dim yellow",
    "step":  "bold cyan",
}), highlight=False)

# ── Paths ────────────────────────────────────────────────────────────────────
ROOT          = Path(__file__).resolve().parent
LSP_ROOT      = ROOT.parent.parent
FIXTURE       = ROOT / "fixtures" / "kitchen-sink.tomlp"
EXPECTED      = ROOT / "fixtures" / "expected.json"
HARNESS_DIR   = ROOT / "harness"
TARGET_RELEASE = LSP_ROOT / "target" / "release"

IS_WINDOWS = os.name == "nt"
EXE = ".exe" if IS_WINDOWS else ""

# ── Tooling sanity ───────────────────────────────────────────────────────────
def which(name: str) -> Path | None:
    p = shutil.which(name)
    return Path(p) if p else None

# ── JSON normalisation + deep-compare ────────────────────────────────────────
def normalise(value: Any) -> Any:
    """Recursively normalise a JSON-decoded value for comparison.

    * dicts → sorted-key dicts (so insertion-order differences vanish)
    * numbers → unified to float for tolerance-based comparison
    * everything else → identity
    """
    if isinstance(value, dict):
        return {k: normalise(value[k]) for k in sorted(value)}
    if isinstance(value, list):
        return [normalise(v) for v in value]
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return float(value)
    return value

def deep_diff(actual: Any, expected: Any, path: str = "$") -> list[str]:
    """Return human-readable diff lines (empty list = identical)."""
    if isinstance(expected, dict):
        if not isinstance(actual, dict):
            return [f"{path}: expected dict, got {type(actual).__name__}"]
        diffs = []
        a_keys, e_keys = set(actual), set(expected)
        for k in sorted(e_keys - a_keys): diffs.append(f"{path}.{k}: missing")
        for k in sorted(a_keys - e_keys): diffs.append(f"{path}.{k}: unexpected")
        for k in sorted(a_keys & e_keys):
            diffs += deep_diff(actual[k], expected[k], f"{path}.{k}")
        return diffs
    if isinstance(expected, list):
        if not isinstance(actual, list):
            return [f"{path}: expected list, got {type(actual).__name__}"]
        if len(actual) != len(expected):
            return [f"{path}: list length {len(actual)} != {len(expected)}"]
        diffs = []
        for i, (a, e) in enumerate(zip(actual, expected)):
            diffs += deep_diff(a, e, f"{path}[{i}]")
        return diffs
    if isinstance(expected, float) and isinstance(actual, float):
        if math.isnan(expected) and math.isnan(actual): return []
        if math.isclose(actual, expected, rel_tol=1e-9, abs_tol=1e-12): return []
        return [f"{path}: {actual!r} != {expected!r}"]
    if actual == expected:
        return []
    return [f"{path}: {actual!r} != {expected!r}"]

# ── Harness definitions ──────────────────────────────────────────────────────
@dataclass
class Harness:
    name: str
    cmd:  list[str]
    cwd:  Path | None = None
    setup: list[list[str]] | None = None
    env:   dict[str, str] | None = None
    skip_reason: str | None = None

def discover_harnesses() -> list[Harness]:
    fixture = str(FIXTURE)
    harnesses: list[Harness] = []

    # Rust CLI — the canonical reference. Always available locally.
    tomlpr = TARGET_RELEASE / f"tomlpr{EXE}"
    if tomlpr.exists():
        harnesses.append(Harness("rust-cli", [str(tomlpr), "parse", fixture]))
    else:
        harnesses.append(Harness("rust-cli", [], skip_reason="tomlpr not built"))

    # Python — assumes the wheel is `pip install`-able in the current env.
    harnesses.append(Harness(
        "python",
        [sys.executable, str(HARNESS_DIR / "python.py"), fixture],
    ))

    # Node native — assumes `tomlplus` resolves (the workspace npm package).
    node = which("node")
    if node:
        node_pkg = LSP_ROOT / "crates" / "tomlplus-node"
        harnesses.append(Harness(
            "node",
            [str(node), str(HARNESS_DIR / "node.js"), fixture],
            cwd=node_pkg,
        ))
        # WASM — uses the pkg-node build relative to the wasm crate.
        wasm_pkg = LSP_ROOT / "crates" / "tomlplus-wasm" / "pkg-node" / "tomlplus_wasm.js"
        if wasm_pkg.exists():
            harnesses.append(Harness(
                "wasm",
                [str(node), str(HARNESS_DIR / "wasm.mjs"), fixture],
            ))
        else:
            harnesses.append(Harness("wasm", [], skip_reason="pkg-node/ not built"))
    else:
        harnesses.append(Harness("node", [], skip_reason="node not installed"))
        harnesses.append(Harness("wasm", [], skip_reason="node not installed"))

    # Ruby
    ruby = which("ruby")
    if ruby:
        env = os.environ.copy()
        ffi_lib = TARGET_RELEASE / f"tomlplus_ffi{'.dll' if IS_WINDOWS else ''}"
        if ffi_lib.exists():
            env["TOMLPLUS_LIB"] = str(ffi_lib)
        harnesses.append(Harness(
            "ruby",
            [str(ruby), "-I", str(LSP_ROOT / "bindings" / "tomlplus-ruby" / "lib"),
             str(HARNESS_DIR / "ruby.rb"), fixture],
            env=env,
        ))
    else:
        harnesses.append(Harness("ruby", [], skip_reason="ruby not installed"))

    # Go
    go = which("go")
    if go:
        env = os.environ.copy()
        # cgo args
        env["CGO_ENABLED"] = "1"
        env["CGO_CFLAGS"]  = f"-I{LSP_ROOT / 'crates' / 'tomlplus-ffi' / 'include'}"
        env["CGO_LDFLAGS"] = f"-L{TARGET_RELEASE}"
        # Loader path for the runtime DLL
        sep = ";" if IS_WINDOWS else ":"
        env["PATH"] = f"{TARGET_RELEASE}{sep}{env['PATH']}"
        harnesses.append(Harness(
            "go",
            [str(go), "run", ".", fixture],
            cwd=HARNESS_DIR / "go",
            env=env,
        ))
    else:
        harnesses.append(Harness("go", [], skip_reason="go not installed"))

    # Java — via Gradle's application plugin run task.
    # Bootstrap a local Gradle if `gradle` isn't on PATH.
    gradle = which("gradle")
    if not gradle:
        # Use the Java-binding's bootstrapped install if it exists.
        for v in ("8.10.2", "8.11", "8.12"):
            cand = LSP_ROOT / "bindings" / "tomlplus-java" / ".gradle-local" / f"gradle-{v}" / "bin" / ("gradle.bat" if IS_WINDOWS else "gradle")
            if cand.exists():
                gradle = cand
                break
    if gradle:
        env = os.environ.copy()
        env["TOMLPLUS_LIB_DIR"] = str(TARGET_RELEASE)
        harnesses.append(Harness(
            "java",
            [str(gradle), "-q", "--no-daemon", "run", f"--args={fixture}"],
            cwd=HARNESS_DIR / "java",
            env=env,
        ))
    else:
        harnesses.append(Harness("java", [], skip_reason="gradle not available"))

    # .NET
    dotnet = which("dotnet")
    if dotnet:
        env = os.environ.copy()
        sep = ";" if IS_WINDOWS else ":"
        env["PATH"] = f"{TARGET_RELEASE}{sep}{env['PATH']}"
        harnesses.append(Harness(
            "dotnet",
            [str(dotnet), "run", "--project",
             str(HARNESS_DIR / "dotnet" / "Harness.csproj"),
             "--", fixture],
            env=env,
        ))
    else:
        harnesses.append(Harness("dotnet", [], skip_reason="dotnet not installed"))

    return harnesses

# ── Runner ───────────────────────────────────────────────────────────────────
def run_harness(h: Harness) -> tuple[str, str, list[str], str | None]:
    """Returns (status, stdout-summary, diffs, skip_reason)."""
    if h.skip_reason:
        return ("skip", "", [], h.skip_reason)
    try:
        r = subprocess.run(h.cmd, cwd=str(h.cwd) if h.cwd else None,
                           env=h.env, capture_output=True, text=True,
                           timeout=180)
    except subprocess.TimeoutExpired:
        return ("fail", "", ["timed out after 180s"], None)
    if r.returncode != 0:
        snippet = (r.stderr or r.stdout).strip().splitlines()[-3:]
        return ("fail", "", [f"exit {r.returncode}", *snippet], None)
    try:
        actual = json.loads(r.stdout)
    except json.JSONDecodeError as e:
        snippet = r.stdout.strip().splitlines()[:2]
        return ("fail", "", [f"invalid JSON: {e}", *snippet], None)
    return ("ok", "", [], None)  # will be filled in by caller

def main() -> int:
    console.print()
    console.print("[step]TOML+ cross-binding integration test[/step]")
    console.print(f"[dim]Fixture: {FIXTURE.relative_to(LSP_ROOT)}[/dim]")
    console.print(f"[dim]Baseline: {EXPECTED.relative_to(LSP_ROOT)}[/dim]")

    expected = normalise(json.loads(EXPECTED.read_text(encoding="utf-8")))

    harnesses = discover_harnesses()
    results: list[tuple[str, str, str, list[str]]] = []  # (name, status, msg, diffs)

    for h in harnesses:
        console.print(f"\n[dim]▸[/dim] running [bold]{h.name}[/bold] …")
        if h.skip_reason:
            results.append((h.name, "skip", h.skip_reason, []))
            console.print(f"  [skip]⊘ skipped — {h.skip_reason}[/skip]")
            continue
        try:
            r = subprocess.run(h.cmd, cwd=str(h.cwd) if h.cwd else None,
                               env=h.env, capture_output=True, text=True,
                               timeout=180)
        except subprocess.TimeoutExpired:
            results.append((h.name, "fail", "timed out", []))
            console.print(f"  [fail]✗ timed out[/fail]")
            continue
        if r.returncode != 0:
            tail = (r.stderr or r.stdout).strip().splitlines()[-3:]
            results.append((h.name, "fail", f"exit {r.returncode}", tail))
            console.print(f"  [fail]✗ exit {r.returncode}[/fail]")
            for line in tail:
                console.print(f"    [dim]{line}[/dim]")
            continue
        try:
            actual = normalise(json.loads(r.stdout))
        except json.JSONDecodeError as e:
            results.append((h.name, "fail", f"invalid JSON: {e}", []))
            console.print(f"  [fail]✗ invalid JSON: {e}[/fail]")
            continue
        diffs = deep_diff(actual, expected)
        if diffs:
            results.append((h.name, "fail", f"{len(diffs)} difference(s)", diffs[:10]))
            console.print(f"  [fail]✗ {len(diffs)} difference(s):[/fail]")
            for d in diffs[:10]:
                console.print(f"    [dim]{d}[/dim]")
            if len(diffs) > 10:
                console.print(f"    [dim]… {len(diffs) - 10} more[/dim]")
        else:
            results.append((h.name, "ok", "", []))
            console.print(f"  [ok]✓ matches baseline[/ok]")

    # ── Summary table ────────────────────────────────────────────────────────
    console.print()
    table = Table(title="Cross-binding summary", show_header=True, header_style="bold cyan")
    table.add_column("binding", style="bold")
    table.add_column("result")
    table.add_column("detail", style="dim")
    for name, status, msg, _ in results:
        if   status == "ok":   sty = "[ok]✓ pass[/ok]"
        elif status == "skip": sty = "[skip]⊘ skip[/skip]"
        else:                  sty = "[fail]✗ fail[/fail]"
        table.add_row(name, sty, msg)
    console.print(table)

    failed = [r for r in results if r[1] == "fail"]
    if failed:
        console.print()
        console.print(f"[fail]{len(failed)} binding(s) failed.[/fail]")
        return 1
    skipped = [r for r in results if r[1] == "skip"]
    ok_count = len(results) - len(skipped)
    console.print()
    console.print(f"[ok]✓ all {ok_count} active binding(s) agree[/ok]"
                  + (f" [dim]({len(skipped)} skipped)[/dim]" if skipped else ""))
    return 0

if __name__ == "__main__":
    sys.exit(main())
